name: ruff-format

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare test environment
        uses: ./.github/actions/prepare-test-environment
      - name: ruff-format
        run: ruff format --check
